version: '3.8'

services:
  cv-app:
    build: .
    container_name: computer-vision-app
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for development
      - .:/app
      # Mount data directory for datasets
      - ./data:/app/data
      # Mount models directory
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
      - DISPLAY=${DISPLAY:-:0}
    # For GUI applications (optional)
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    stdin_open: true
    tty: true
    
  # Optional: Jupyter notebook service
  jupyter:
    build: .
    container_name: cv-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONPATH=/app
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    profiles:
      - jupyter